version: '3.7'
services:
  metadata_app:
    build: ./app
    image: streamlitapp:latest
    container_name: creditapp
    ports:
      - "80"
    tty: true

    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=mohamed"
      - "traefik.frontend.rule=Host:mohamed.localhost"
      - "traefik.port=80"
networks:
  traefik:
    

  